import Head from "next/head";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Prepp Photographer Resources and Marketing Kit</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <div>
          <h1>Hello World</h1>
        </div>
      </main>

      <footer>
        Created by <span>Prepp Photo</span>
      </footer>
    </div>
  );
}
