import Head from "next/head";
import Header from "../components/Header";

const Home = () => {
  return (
    <div>
      <Head>
        <title>Prepp Photographer Resources and Marketing Kit</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <div>
          <Header />
        </div>
      </main>

      <footer>
        Created by <span>Prepp Photo</span>
      </footer>
    </div>
  );
};

export default Home;
